### ISSUE TITLE
데이터마이닝

### ISSUE THREAD

**Issue by milooy** [9XDM/YOP#1]
- 워드클라우드
    - https://www.jasondavies.com/wordcloud/
- 언급된 프로그래밍언어 순위 도넛차트
    - http://www.chartjs.org/docs/#doughnut-pie-chart-introduction

**Comment by qkraudghgh** [comment]
- konlpy twitter class
  - http://konlpy.org/ko/v0.4.3/api/konlpy.tag/#module-konlpy.tag._twitter
- What is TF-IDF
  - https://ko.wikipedia.org/wiki/TF-IDF

- 생각해본 Visualization
  1. 모든 회고글의 Word Cloud
  2. 회고글에서 가장 언급이 많이 됐던 Programming Language 도넛 차트

**Comment by kyunooh** [comment]
TF-IDF에 대해선 한글 위키는 정규화 로직이 잘 안알려져 있어서 영문 위키 추천드립니다. 정보의 질이 달라요.
https://en.wikipedia.org/wiki/Tf%E2%80%93idf

**Comment by qkraudghgh** [comment]
우리가 아마 javascript project​될 것 같아서 형태소 분석 라이브러리는 nodeJS로 Wrapping된걸 찾아봤습니다.
- [node-twitter-korean-text](https://github.com/rokoroku/node-twitter-korean-text)
- [twtkrjs](https://github.com/Ch0p/twtkrjs)

회고글에서 가장 언급이 많이 됐던 Programming Language는 그냥 javascript에서 Text search해서 만들어주면 될 것 같아서 일단 방법을 강구해보겠습니다.
​

**Comment by qkraudghgh** [comment]
```javascript
"Javascript, javascript, 자바스크립트, 파이썬, python, python".match(/javascript|python|파이썬|자바스크립트/g);

>> ["javascript", "자바스크립트", "파이썬", "python", "python"]
```

이런식으로 Text Search 해서 Grouping해서 Counting하면 될 것 같습니다.

Lodash를 쓰면

```javascript
const blogPosts = "Javascript, javascript, 자바스크립트, 파이썬, python, python";
const langRegex = /javascript|python|파이썬|자바스크립트/g;
const languages = _.toLower(blogPosts).match(langRegex);

console.log(languages);
>> ["javascript", "javascript", "자바스크립트", "파이썬", "python", "python"]

console.log(_.countBy(languages));
>> Object {javascript: 2, 자바스크립트: 1, 파이썬: 1, python: 2}
```

이런식으로 될꺼고 `python과 파이썬`을 동일하게 인식해 Count하도록 짜면 되겠군요

**Comment by qkraudghgh** [comment]
# node-twitter-korean-text Usage

node-java를 사용하므로 local에 java가 깔려있어야합니다.

```bash
npm install --save node-twitter-korean-text
```

```javascript
'use strict';
const TwitterKoreanProcessor = require('node-twitter-korean-text');

TwitterKoreanProcessor.normalize('아버지 가방에 들어가신다.').then(result => {
  TwitterKoreanProcessor.tokenize(result).then((token) => {
    TwitterKoreanProcessor.tokensToJsonArray(token, true).then(results => {
      for(let i=0; i < results.length; i++) {
        const temp = results[i];
        if (temp["koreanPos"] === 'Noun') {
          console.log(temp["text"]);
        }
      }
    })
  });
});

>> 아버지
>> 가방
```
