### ISSUE TITLE
QA: post.write.component.ts Auth State Exception Problem

### ISSUE THREAD

**Issue by uyu423** [9XDM/YOP#10]
역시나 알려진 문제인지는 모르겠으나 내일 오픈하신다기에 작성해봅니다.

큰문제는 아니건 같지만 wirte post 페이지에서 로그아웃 시 메인으로 이동하지 않고 다음과 같은 상태가 됩니다.
![image](https://cloud.githubusercontent.com/assets/8033320/22262291/b0c6d368-e2b3-11e6-8c05-8a0384bfbc39.png)

마찬가지로 `https://yop.cool/posts/write/new` URL로 직접 접근 시 같은 현상입니다.

```typescript
    this.authService.getSession()
      .take(1)
      .subscribe(session => {
        this.user = session.auth

        this.http.get(`${Github.API_USER}/${session.auth.providerData[0].uid}`).subscribe(res => {
          this.user.githubURL = res.json().html_url; // hard coding.. for getting githubURL
        })
      });
```
`session.auth`가 `null` 일 때, 예외처리가 필요할 것 같습니다.

여담으로 Network 탭을 살펴보니 googleapi에서 `getAccountInfo`를 두번 받아오는 것 같습니다. 
![image](https://cloud.githubusercontent.com/assets/8033320/22262596/eb6249fc-e2b4-11e6-9bc6-4eba03d4168f.png)
Call 되는 위치는 다른데 res body는 동일합니다. 이런게 동작하는 다른 이유가 있는지 궁금합니다.

**Comment by qkraudghgh** [comment]
@uyu423 
일단은 세션 체크를 해서 로그인 세션이 없으면 메인으로 튕기게 해놨습니다.

아래 zone이랑 firebase에서 동일한 body를 불러오는건 제가 angular2를 아직 잘 몰라서 좀더 봐야겠네요 
일단 이상은 없으니 추후에 수정하겠습니다.

**Comment by uyu423** [comment]
056859fd7770bf0a6b3a300c067737d6398a7c11 에서 해결됨. close

getAccountInfo 2번 호출되는 것은 당장 사용하는데 큰 문제는 없다고 판단됩니다.
